### ISSUE TITLE
Some small mistakes

### ISSUE THREAD

**Issue by who3m1** [fox-one/docs.pando.im#58]
- Pando Lake & 4swap
   - API Reference
      - [Authorization](https://docs.pando.im/developer/lake/apis/auth)

Endpoint URL 应该是 https://api.4swap.org/api/oauth

Example Request 里的 curl 语句无法执行，URL后面缺少了双引号，PAYLOAD前面也少了双引号
应该改成 `curl -X POST "https://api.4swap.org/api/oauth" --data "PAYLOAD" -H "Content-Type: application/json" `

---

- Pando Leaf
   -  API Reference
      - Read Vaults
        - [Read Single Vault](https://docs.pando.im/developer/leaf/apis/vaults#read-single-vault)

用 https://leaf-api.pando.im/api/me/vats 获取到 vaults的id，去查 https://leaf-api.pando.im/api/vat/:id 会返回404

文档里Read Single Vault 的Endpoint URL有误，实际路径是 https://leaf-api.pando.im/api/vats/:id

Example request 也无法执行, 应该改成 `curl -X GET "https://leaf-api.pando.im/api/vats/52010fd0-6a9d-393c-abcb-ca997d950bf5" -H "Content-Type: application/json" `

---

- Pando Leaf
   -  API Reference
      - [Create Actions](https://docs.pando.im/developer/leaf/apis/actions)

Example request里需要Bearer Token，但Authentication and options里写的是Public access，应该改成Authorized。

**Comment by lyricat** [comment]
fixed in 2876063e951c9ee90fa2c21fa6f4890dc78edfe4

**Comment by lyricat** [comment]
thank you for the correction
